# 저장소 소유자의 요청에 따라 이 파일은 Git에 포함합니다.
# Aiven Console > Service > Overview > Connection information 값을 붙여 넣으세요.
aiven.mysql.host=findguni-fundguni.j.aivencloud.com
aiven.mysql.port=12343
aiven.mysql.database=defaultdb
aiven.mysql.username=avnadmin
aiven.mysql.password=AVNS_Hb2xm4wDeo4WPGG20Pd
